#!/usr/bin/env zsh

mysql-truncate-database() {
    local -r progname="${0##*/}"
    local help

    zmodload zsh/zutil
    zparseopts -D -F -K -- {h,-help}=help || return 1

    if [[ $# -eq 0 ]] || [[ -n "${help}" ]]; then
        echo -n "
Usage: ${progname} <database>

Example:

  ${progname} my-blog
"
        return 0
    fi

    for table in $(mysql -Nse 'SHOW TABLES' "${1}"); do
        command mysql -e "TRUNCATE TABLE '${table}'" "${1}"
    done
}

mysql-truncate-database "$@"
