#!/usr/bin/env zsh

PROGNAME=${0##*/}

if [[ $# -eq 0 ]]; then
    echo "Usage: $PROGNAME database_name [user_name]"
    exit 1
fi

DATABASE=$1
USER=$2
CHARACTER_SET=${CHARACTER_SET=utf8}
COLLATION=${COLLATION=utf8_general_ci}

CREATE_DATABASE_QUERY="CREATE DATABASE $DATABASE CHARACTER SET $CHARACTER_SET COLLATE $COLLATION"

if [[ -n $USER ]]; then
    if [[ $(echo $USER | grep -c '@') -eq 0 ]]; then
        USER="$USER@localhost"
    fi
    CREATE_DATABASE_QUERY="$CREATE_DATABASE_QUERY; GRANT ALL PRIVILEGES ON $DATABASE.* TO $USER"
fi

mysql -e $CREATE_DATABASE_QUERY
