#!/usr/bin/env zsh

PROGNAME=${0##*/}

if [[ $# -eq 0 ]]; then
    echo "Usage: $PROGNAME user_name [password]"
    exit 1
fi

USER=$1
if [[ $(echo $USER | grep -c '@') -eq 0 ]]; then
    USER="$USER@localhost"
fi

PASSWORD=$2
if [[ -z $PASSWORD ]]; then
    echo -n "Enter user password: \n"; read -s PASSWORD
fi

PASSWORD_HASH=$(mysql -e "SELECT PASSWORD('$PASSWORD')" | grep '\*\w*')

CREATE_USER_QUERY="CREATE USER \`${USER/@/\`@\`}\` IDENTIFIED BY PASSWORD '$PASSWORD_HASH'"

mysql -e $CREATE_USER_QUERY
